export const APP_URL = {
  HOME: "/",
  ABOUT: "/about",
  TERMS: "/terms",
  CONTACT: "/contact",
  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  APP: "/app",
  APP_CHAT: "/app/chat",
  APP_ASK_AI: "/app/ask-ai",
  APP_PROFILE: "/app/profile",
  APP_PROFILE_INFO: "/app/profile/info",
  ADMIN: "/admin",
  ADMIN_USER_MANAGEMENT: "/admin/user",
  ADMIN_CARE_SKIN_MANAGEMENT: "/admin/skins",
  ADMIN_CHATS: "/admin/chats",
};
